Cart screen
MikhailZavyalov/iOS-FakeNFT-StarterProject-Public pull request #23
Opened 2023-07-11 11:05 UTC by uglyqurill

Доделал всю верстку и логику в CartScreen. Всё работает пока что на моковых данных. Небольшие косметические фиксы добавлю в скором времени.

Если менять экраны TabBar то корзина обновляет моковые данные просто для удобства. После процесс покупки кнопка возвращает опять в корзину тоже чисто для удобства. Дальше делать, думаю, смысл будет уже при полноценной работе приложения.

2023-07-11 11:51 UTC, LobanovaViktoria requested changes
Все отлично! 
Можно добавить cell.selectionStyle = .none в  cellForRowAt

2023-07-11 14:34 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/CartViewController.swift
> +        button.addTarget(self, action: #selector(cancelDeletion), for: .touchUpInside)
и тут тоже

2023-07-11 14:48 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/MockCartData.swift
> +    NFT(id: UUID(),
Тут можно поправить отступы

2023-07-11 14:52 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/CartViewController.swift
> +            sortButton.addTarget(self, action: #selector(showSortingOptions), for: .touchUpInside)
переместить во viewDidLoad

2023-07-11 14:57 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/CartViewController.swift
> +        setupView()
```
addedNFTs = MockCartData.nfts
setupView()
```
лучше переместить во `viewDidLoad`, т.к viewWillAppear вызывается каждый раз при появлении экрана, а не один раз при создании, и каждый раз будет выполняться этот код (из за этого например если удалить продукты из корзины, переключиться на другую вкладку и обратно на эту, то продукты снова появятся)

2023-07-11 14:59 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/CartViewController.swift
> +        setupView()
сам override viewWillAppear в таком случае можно будет удалить

2023-07-11 15:08 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/CryptoCurrencyViewController.swift
> +        button.addTarget(self, action: #selector(backButtonTapped), for: .touchUpInside)
переместить во viewDidLoad

2023-07-11 15:08 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/CryptoCurrencyViewController.swift
> +        collectionView.register(PaymentCell.self, forCellWithReuseIdentifier: PaymentCell.reuseIdentifier)
переместить во viewDidLoad

2023-07-11 15:11 UTC, MikhailZavyalov commented on FakeNFT/Scenes /Cart/VC/PurchaseResultViewController.swift
> +        button.addTarget(self, action: #selector(paymentResultTapped), for: .touchUpInside)
переместить во viewDidLoad

2023-07-16 19:42 UTC, LobanovaViktoria approved these changes

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/DesignSystem/Colors.swift
> +    static let ypRed = UIColor(named: "ypRed")
Рекомендую использовать библиотеки генерации ресурсов вроде [SwiftGen](https://github.com/SwiftGen/SwiftGen). Понимаю, что нужно было договориться с командой. Но в будущих проектах очень пригодится. Избавит от многих проблем.

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Extentions/Observable.swift
> +    }
Биндинги хорошо реализованы. Но уже сейчас рекомендую начать знакомиться с реактивщиной. Концепция не самая простая, но скоро будет необходима в связке SwiftUI+Combine.

[Неплохая вводная статья](https://habr.com/ru/companies/simbirsoft/articles/712332/)

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Scenes /Cart/Model/CartModel.swift
> +                var nfts: [NFTServerModel] = []
Подобные сущности лучше делать классами, чтобы, если что, ее значение не копировалось, а передавалось по ссылке.
[Value Types vs Reference Types, and When to Use Each](https://www.codementor.io/blog/value-vs-reference-6fm8x0syje)

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Scenes /Cart/Model/CartModel.swift
> +struct CartModel {
Название `CartModel` больше подойдет для описания структуры, которая содержит в себе просто некоторые свойства. Более подходящим будет, например, `CartContentLoader`

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Scenes /Cart/Model/CartModel.swift
> +        networkClient.send(request: request, type: CartServerModel.self, onResponse: completion)
Лучше базовый урл вынести в константы. Так нам, в случае необходимости, не придется его менять во многих местах.

И рекомендую как можно реже использовать force unwrap. Лучше обработать с помощью guard-let

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Scenes /Cart/View/VC/CryptoCurrencyViewController.swift
> +    }
8 - [магическое число](https://bureau.ru/soviet/20230406/).  Лучше такого избегать. 

Нужно добавить енуму `Cryptocurrency` соответствие протоколу `CaseIterable` и спользовать так:
```
return Cryptocurrency.allCases.count
```

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Scenes /Cart/View/VC/CryptoCurrencyViewController.swift
> +}
Рекомендую вынести спэйсинги в переменные или в отдельную структуру.

2023-07-17 17:17 UTC, Helvetii951 commented on FakeNFT/Scenes /Cart/ViewModel/CartViewModel.swift
> +    var NFTmodels: [NFTModel] = []
В  Swift принято называть свойства в camelCase.

2023-07-23 10:23 UTC, merged